### ISSUE TITLE
Release version 1.0

### ISSUE THREAD

**Issue by rshamsundar** [ascom-au/apache-role#1]
Release procedure https://119.9.13.178/iwsoftware/wiki/Processes/Release/AnsibleRoles

**Comment by serg89** [comment]
Following the release procedure here: https://119.9.13.178/iwsoftware/wiki/Processes/Release/AnsibleRoles

- [x] Ensure that there is an issue for the release in the release milestone in order to track any changes required
- [x] Ensure that all issues assigned to the release milestone have been closed (except for the release issue)
- [x] Ensure that all issues that have resulted in commits have been closed (you will need to dig through the commit messages because many of the issues will belong to playbook projects)
- [x] Ensure that all issue specific branches have been merged and removed 

- [x] Create a tag for the release version
- [x] Close the release issue
- [x] Close the milestone
- [x] Create a milestone for the next release by creating the issue to release the next version 
- [x] Create a new 1.0 branch for future development

**Comment by serg89** [comment]
Tickets and issues included in this release:

- [x] ascom-au/install-iso#3

**Comment by serg89** [comment]
Checking the following projects for branch merges/removal:

ascom-au/install-iso#3 - branch merging/removal completed.

**Comment by serg89** [comment]
Created the release_1.0 tag, https://github.com/ascom-au/apache-role/releases/tag/release_1.0

**Comment by serg89** [comment]
Created the following milestones:

v1.0.1
v1.1

See https://github.com/ascom-au/apache-role/milestones

**Comment by serg89** [comment]
Created new branch https://github.com/ascom-au/apache-role/tree/branch_1.0

**Comment by serg89** [comment]
Created issues for the v1.0.1 and v1.1 releases:

https://github.com/ascom-au/apache-role/issues/2
https://github.com/ascom-au/apache-role/issues/3

**Comment by zhousidun82** [comment]
## Review:
Review passed. Closing this ticket.
